apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: staging
  labels:
    type: local 
    part-of: nexus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  labels: 
    part-of: nexus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
