apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: staging
spec:
  selector: 
    app: nexus-server
    part-of: nexus
  type: NodePort  
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32000